language: go

jobs:
  include:
      - stage: checks
        name: "Format"
        script: make check
      - stage: checks
        name: "Lint"
        script: make lint
      - stage: checks
        name: "Verify"
        script:
          - go mod download
          - make vet
      - stage: test
        script: make test

env:
  - GO111MODULE=on
