language: go

jobs:
  include:
      - stage: lint
        script: make check
      - stage: lint
        script: make lint
      - stage: lint
        script:
          - go mod download
          - make vet
      - stage: test
        script: make test

env:
  - GO111MODULE=on
