version: 2

jobs:
  # Ensure code is formatted correctly
  format:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Run check
          command: make check
  # Run linter
  lint:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: Run linting
          command: make lint
  # Verify the code
  verify:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Run verification
          command: make vet
  # Test the code
  test:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install tools
          command: make install-tools
      - run:
          name: Run tests
          command: make coverage
  # Build docs
  docs-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
          working_directory: ./docs
      - run:
          name: Build docs
          command: yarn build
          working_directory: ./docs
      - persist_to_workspace:
          root: .
          paths: docs/public
  # Deploy docs
  docs-deploy:
    docker:
      - image: node:8.10.0  # We need this for the javascript tool
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure dependencies
          command: npm install -g --silent gh-pages@2.0.1
      - run:
          name: Configure git
          command: |
            git config user.email "ci-build@sambriggs.dev"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ca:db:bd:d8:2f:18:ea:a9:a9:54:21:92:97:a6:5c:68"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --dist ./docs/public --message "[ci skip] Deploy documentation updates"
workflows:
  version: 2
  main:
    jobs:
      - format
      - lint
      - verify
      - test
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master
